#!/usr/bin/env python3
"""
Mock inventory data based on Shottenkirk Toyota San Antonio
This represents realistic data that would be scraped from their website
"""

from datetime import datetime, timezone

SHOTTENKIRK_TOYOTA_INVENTORY = {
    "dealership": "Shottenkirk Toyota San Antonio",
    "total_vehicles": 268,
    "new_vehicles": 190,
    "used_vehicles": 78,
    "last_updated": datetime.now(timezone.utc).isoformat(),
    "vehicles": [
        # New 2025/2026 Toyota Vehicles from actual inventory
        {
            "vin": "4T1DAACK1SU207179",
            "stock_number": "43185",
            "year": 2025,
            "make": "Toyota",
            "model": "Camry",
            "trim": "XSE",
            "body_style": "Sedan",
            "condition": "new",
            "price": 42118,
            "original_price": 42118,
            "savings": 0,
            "exterior_color": "Supersonic Red with Midnight Black Metallic roof",
            "interior_color": "Black",
            "description": "2025 Toyota Camry XSE - Sedan",
            "images": ["https://vehicle-photos-published.vauto.com/b0/f8/c8/20-9864-4c91-aba8-93c6593252aa/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/Camry/4T1DAACK1SU207179/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "2T3A1RFV4SW577282",
            "stock_number": "42895", 
            "year": 2025,
            "make": "Toyota",
            "model": "RAV4",
            "trim": "XLE Premium",
            "body_style": "Utility",
            "condition": "new",
            "price": 38769,
            "original_price": 40160,
            "savings": 1391,
            "exterior_color": "Blueprint",
            "interior_color": "Black SofTex®",
            "description": "2025 Toyota RAV4 XLE Premium - Utility",
            "images": ["https://vehicle-photos-published.vauto.com/86/0b/7b/a1-8c61-497b-9432-dbda66c798e6/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/RAV4/2T3A1RFV4SW577282/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "3TYLC5LN9ST041305",
            "stock_number": "42860",
            "year": 2025,
            "make": "Toyota", 
            "model": "Tacoma i-FORCE MAX",
            "trim": "TRD Sport",
            "body_style": "Double cab 5-ft bed",
            "condition": "new",
            "price": 49699,
            "original_price": 52487,
            "savings": 2788,
            "exterior_color": "Ice Cap",
            "interior_color": "Boulder/Black Fabric w/Smoke Silver",
            "description": "2025 Toyota Tacoma i-FORCE MAX TRD Sport - Double cab 5-ft bed",
            "images": ["https://vehicle-photos-published.vauto.com/77/3f/21/08-292c-4a8d-a11e-d32d897f11c9/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851", 
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/Tacoma-i-FORCE-MAX/3TYLC5LN9ST041305/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "5TFMC5DB8TX118598",
            "stock_number": "43139",
            "year": 2026,
            "make": "Toyota",
            "model": "Tundra i-FORCE MAX", 
            "trim": "1794 Edition",
            "body_style": "Crewmax 5.5-Ft.",
            "condition": "new",
            "price": 76955,
            "original_price": 78955,
            "savings": 2000,
            "exterior_color": "Wind Chill Pearl",
            "interior_color": "Saddle Tan Leather-trimmed",
            "description": "2026 Toyota Tundra i-FORCE MAX 1794 Edition - Crewmax 5.5-Ft.",
            "images": ["https://vehicle-photos-published.vauto.com/14/a7/54/0e-a81b-46d0-b3dc-4c815c426f1c/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2026/Toyota/Tundra-i-FORCE-MAX/5TFMC5DB8TX118598/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "5YFB4MCE9SP252687",
            "stock_number": "43039",
            "year": 2025,
            "make": "Toyota",
            "model": "Corolla",
            "trim": "FX",
            "body_style": "Sedan",
            "condition": "new", 
            "price": 29485,
            "original_price": 29485,
            "savings": 0,
            "exterior_color": "Midnight Black Metallic",
            "interior_color": "Moonstone Premium Fabric w/ Orange Stitching",
            "description": "2025 Toyota Corolla FX - Sedan",
            "images": ["https://vehicle-photos-published.vauto.com/13/e7/0f/5b-6e0d-423f-beb0-47c1e8aeb432/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/Corolla/5YFB4MCE9SP252687/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "4T1DAACK0TU213329", 
            "stock_number": "43150",
            "year": 2026,
            "make": "Toyota",
            "model": "Camry",
            "trim": "Nightshade",
            "body_style": "Sedan", 
            "condition": "new",
            "price": 37826,
            "original_price": 37826,
            "savings": 0,
            "exterior_color": "Midnight Black Metallic",
            "interior_color": "Black",
            "description": "2026 Toyota Camry Nightshade - Sedan",
            "images": ["https://vehicle-photos-published.vauto.com/e4/8f/8a/ca-43c9-4998-814d-78a2a26ef307/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio", 
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2026/Toyota/Camry/4T1DAACK0TU213329/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "3TMLB5JN9SM162594",
            "stock_number": "42753",
            "year": 2025,
            "make": "Toyota",
            "model": "Tacoma",
            "trim": "SR5",
            "body_style": "Double cab 5-ft bed",
            "condition": "new",
            "price": 41499,
            "original_price": 43453, 
            "savings": 1954,
            "exterior_color": "Underground",
            "interior_color": "Boulder Fabric w/Smoke Silver",
            "description": "2025 Toyota Tacoma SR5 - Double cab 5-ft bed",
            "images": ["https://vehicle-photos-published.vauto.com/91/74/89/a9-f95b-4bf6-9c12-cacfe6990c7e/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851", 
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/Tacoma/3TMLB5JN9SM162594/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "2T3H1RFV1SW421909",
            "stock_number": "43119",
            "year": 2025,
            "make": "Toyota",
            "model": "RAV4", 
            "trim": "LE",
            "body_style": "Utility",
            "condition": "new",
            "price": 34501,
            "original_price": 34501,
            "savings": 0,
            "exterior_color": "Ice Cap", 
            "interior_color": "Black Fabric",
            "description": "2025 Toyota RAV4 LE - Utility",
            "images": ["https://vehicle-photos-published.vauto.com/36/fe/bc/f2-a6ec-42a7-9aa4-eecfe740ff13/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/RAV4/2T3H1RFV1SW421909/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "5TFLA5AB3TX051544",
            "stock_number": "43130", 
            "year": 2026,
            "make": "Toyota",
            "model": "Tundra",
            "trim": "SR5",
            "body_style": "Crewmax 5.5-Ft.",
            "condition": "new",
            "price": 55516,
            "original_price": 57516,
            "savings": 2000,
            "exterior_color": "Midnight Black Metallic",
            "interior_color": "Black Fabric", 
            "description": "2026 Toyota Tundra SR5 - Crewmax 5.5-Ft.",
            "images": ["https://vehicle-photos-published.vauto.com/9f/b1/36/70-aa0d-4bfa-b5af-8f2aa4b3ccf7/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232", 
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2026/Toyota/Tundra/5TFLA5AB3TX051544/",
            "last_updated": datetime.now(timezone.utc).isoformat()
        },
        {
            "vin": "4T1DAACK4SU208908",
            "stock_number": "43098",
            "year": 2025,
            "make": "Toyota",
            "model": "Camry",
            "trim": "LE",
            "body_style": "Sedan",
            "condition": "new",
            "price": 32034,
            "original_price": 32034, 
            "savings": 0,
            "exterior_color": "Reservoir Blue",
            "interior_color": "Black",
            "description": "2025 Toyota Camry LE - Sedan",
            "images": ["https://vehicle-photos-published.vauto.com/04/62/cc/67-97f7-4073-b85c-b55109d98973/image-1.jpg"],
            "dealership": "Shottenkirk Toyota San Antonio",
            "dealership_phone": "210.526.2851",
            "dealership_address": "18019 US-281, San Antonio TX 78232",
            "url": "https://www.shottenkirktoyotasanantonio.com/vehicle/New/2025/Toyota/Camry/4T1DAACK4SU208908/", 
            "last_updated": datetime.now(timezone.utc).isoformat()
        }
    ],
    "summary_by_model": {
        "Camry": {"count": 32, "min_price": 28000, "max_price": 42000, "avg_price": 35000},
        "RAV4": {"count": 40, "min_price": 32000, "max_price": 45000, "avg_price": 38500},
        "Tacoma": {"count": 49, "min_price": 35000, "max_price": 65000, "avg_price": 48000},
        "Tundra": {"count": 26, "min_price": 52000, "max_price": 85000, "avg_price": 68000},
        "Corolla": {"count": 16, "min_price": 25000, "max_price": 32000, "avg_price": 28500},
        "Highlander": {"count": 9, "min_price": 38000, "max_price": 55000, "avg_price": 46500},
        "4Runner": {"count": 25, "min_price": 42000, "max_price": 65000, "avg_price": 52000}
    }
}